"""empty message

Revision ID: 68f7f5a60498
Revises: b99551637e5b
Create Date: 2025-06-09 00:06:36.360501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68f7f5a60498'
down_revision = 'b99551637e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favorites_item_uid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'item', ['item_id'], ['id'])
        batch_op.drop_column('item_uid')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('type_item',
               existing_type=postgresql.ENUM('PEOPLE', 'PLANETS', name='itemtypeenum'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('uid',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_constraint('item_uid_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_unique_constraint('item_uid_key', ['uid'])
        batch_op.alter_column('uid',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('type_item',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PEOPLE', 'PLANETS', name='itemtypeenum'),
               existing_nullable=False)

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_uid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_item_uid_fkey', 'item', ['item_uid'], ['uid'])
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
