"""empty message

Revision ID: b99551637e5b
Revises: a5cffa318ac2
Create Date: 2025-06-08 16:51:49.072728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99551637e5b'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_item', sa.Enum('PEOPLE', 'PLANETS', name='itemtypeenum'), nullable=False),
    sa.Column('prop_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prop_id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_uid'], ['item.uid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('propertie_id', sa.String(length=50), nullable=False),
    sa.Column('created', sa.String(length=50), nullable=False),
    sa.Column('edited', sa.String(length=50), nullable=False),
    sa.Column('propertie_1', sa.String(length=100), nullable=False),
    sa.Column('propertie_2', sa.String(length=50), nullable=False),
    sa.Column('propertie_3', sa.String(length=50), nullable=False),
    sa.Column('propertie_4', sa.String(length=50), nullable=False),
    sa.Column('propertie_5', sa.String(length=50), nullable=False),
    sa.Column('propertie_6', sa.String(length=50), nullable=False),
    sa.Column('propertie_7', sa.String(length=50), nullable=False),
    sa.Column('propertie_8', sa.String(length=255), nullable=False),
    sa.Column('propertie_9', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['propertie_id'], ['item.prop_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('propertie_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('member_since', sa.DateTime(), nullable=False))
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('email')
        batch_op.drop_column('password')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.drop_column('member_since')
        batch_op.drop_column('username')

    op.drop_table('properties')
    op.drop_table('favorites')
    op.drop_table('item')
    # ### end Alembic commands ###
